name: 'comissao_516'
version: '1.0.0'
config-version: 2

profile: 'comissao_516'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  comissao_516:
    staging:
      +materialized: table
      +schema: dbt_staging
    intermediate:
      +materialized: table
      +schema: dbt_intermediate
    marts:
      +materialized: table
      +schema: dbt_marts
